### ISSUE TITLE
Confusion over docker images

### ISSUE THREAD

**Issue by wyatt** [billz/raspap-docker#3]
Hi,

Just a little confused about which docker image should be used. In the readme, it specificies that `jrcichra/raspap-docker` should be used, however, this project contains a Dockerfile which differs from that of the image. Would greatly appreciate some assistance! 🙂

**Comment by billz** [comment]
This is based on a systemd-enabled Docker container, per @jrcichra https://github.com/billz/raspap-webgui/issues/458#issuecomment-703143307 

> systemd needs to be the initial process in that container. Users will have to start the container detached, then run the setup script inside, which uses the cURL call.

That said, this is still very early beta.

**Comment by wyatt** [comment]
So what's the point in the Dockerfile in this repo - it doesn't seem to be used anywhere?

**Comment by billz** [comment]
Re-read the last sentence :)
